version: 2.1.{build}
configuration: Release
image: Visual Studio 2017
install:
- git submodule update --init --recursive
build:
  project: ZoraGenWpf.sln
  verbosity: minimal
artifacts:
- path: ZoraGenWpf\bin\$(configuration)\ZoraGen.exe
  name: ZoraGen
